### ISSUE TITLE
first retry fail :(

### ISSUE THREAD

**Issue by khrys63** [ClusterM/nes2wii#3]
Hi

I test with ATMEGA16A, without 16MHz crystal.
I use nes2wii.hex as is, not recompiled.

I use USB ASP Device and WinAVR  for programming ATMEGA16A, and it's ok.

I use pin 1, 2, 3 and 4 for programming.
I map 30 to 37 for Genesis controler
I map 19, 20 and 21for Wii controler (19 & 20 with 2.2k resist to the VCC)

I put a 4.7µF

It didnt work :(

I dont put LED n 15 and 16, is it the problem?
I dont put Crystal, is it the problem?

During test, i've 2.9V between VCC and GND on the ATMEGA16A  (pin 38 and 39)

**Comment by khrys63** [comment]
I use an ATMEGA16A TQFP
and my command line to programming was : avrdude -p atmega16 -P usb -c usbasp -U flash:w:nes2wii.hex
(without Fuse)

**Comment by khrys63** [comment]
New command line : 
avrdude -V -p atmega16 -P usb -c usbasp -U flash:w:nes2wii.hex -U lfuse:w:0xFF:m -U hfuse:w:0xD9:m

I add LED on 15 and 16 pin.

same problem :(

**Comment by ClusterM** [comment]
Fuses FF D9 are for external crystal. You can change fuses to use internal oscillator, but it can work on 8MHz only.

**Comment by khrys63** [comment]
I use http://www.engbedded.com/fusecalc/ to find good fuse for internal 8MHz : C8-D9.

> E:\nes2wii-master>avrdude -V -p atmega16 -P usb -c usbasp -U flash:w:nes2wii.hex -U lfuse:w:0xC8:m -U hfuse:w:0xD9:m
> 
> avrdude: warning: cannot set sck period. please check for usbasp firmware update.
> avrdude: AVR device initialized and ready to accept instructions
> 
> Reading | ################################################## | 100% 0.01s
> 
> avrdude: Device signature = 0x1e9403
> avrdude: NOTE: FLASH memory has been specified, an erase cycle will be performed
>          To disable this feature, specify the -D option.
> avrdude: erasing chip
> avrdude: warning: cannot set sck period. please check for usbasp firmware update.
> avrdude: reading input file "nes2wii.hex"
> avrdude: input file nes2wii.hex auto detected as Intel Hex
> avrdude: writing flash (10000 bytes):
> 
> Writing | ################################################## | 100% 6.41s
> 
> 
> 
> avrdude: 10000 bytes of flash written
> avrdude: reading input file "0xC8"
> avrdude: writing lfuse (1 bytes):
> 
> Writing | ################################################## | 100% 0.02s
> 
> avrdude: 1 bytes of lfuse written
> avrdude: reading input file "0xD9"
> avrdude: writing hfuse (1 bytes):
> 
> Writing | ################################################## | 100% 0.01s
> 
> avrdude: 1 bytes of hfuse written
> 
> avrdude: safemode: Fuses OK
> 
> avrdude done.  Thank you.


It didnt work. LED didn't flash, and gamepad is non functionnal :(

**Comment by ClusterM** [comment]
Do you changed working frequency in defines.h?

**Comment by khrys63** [comment]
No :(

**Comment by khrys63** [comment]
I use hex file as is.
And since my last avrdude, my atmega seems be a brick. I Can reuse or :(

It a very good project, i need it for my retro gaming session but i dont have the knowledge on atmega to finish it

**Comment by khrys63** [comment]
I can't reuse it. (Sorry for my french Android autocompletion)
